apiVersion: v1
kind: Service
metadata:
  name: restsvc
spec:
  selector:
    app: restsvc
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 8888
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: restsvc
spec:
  replicas: 1
  selector:
    matchLabels:
      app: restsvc
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: restsvc
    spec:
      containers:
      - image: docker.pkg.github.com/waynebothaza/restsvc/restsvc:1.0
        name: restsvc
        ports:
        - containerPort: 8888
        env:
          - name: NODE_NAME
            valueFrom:
              fieldRef:
                fieldPath: spec.nodeName
          - name: POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: POD_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          - name: POD_IP
            valueFrom:
              fieldRef:
                fieldPath: status.podIP
        resources: {}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: restsvc
  annotations:
    kubernetes.io/ingress.class: kong
spec:
  rules:
  - http:
      paths:
      - path: /echo
        pathType: Prefix
        backend:
          service:
            name: restsvc
            port:
              number: 80
